# Generated by Django 4.1.3 on 2022-11-16 13:17

from django.db import migrations


def add_superuser(app_registry, schema_editor):
    users = app_registry.get_model("core", "AppUser")
    user = users.objects.create_superuser(
        username="superuser@playground.com", password="change_me"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_superuser, reverse_code=migrations.RunPython.noop)
    ]
