version: "3.8"
name: 'Django Playground'
services:
  django:
    image: playground:latest
    build: 
      context: ../../
      dockerfile: dockerfiles/django/Dockerfile
    container_name: django_app
    command: /bin/bash start.sh
    ports:
      - 8000:8000
    # Bind the mount with it. 

# Integrate Django-debug-toolbar 
# Integrate POSTGRES via env variables

